handlebars:
  suffix: .html

server:
  tomcat:
    accept-count: 1 # 현재 스레드 풀이 모두 사용 중일 때 request에 대한 대기 queue의 사이즈
    max-connections: 10 # 동시에 유지할 수 있는 최대 커넥션 갯수
    threads:
      max: 1 # 워커 스레드의 갯수

